#!/usr/bin/env bash

docker run -e BUILDKITE_BUILD_FOLDER_NAME=$BUILDKITE_BUILD_FOLDER_NAME \
           -e BUILDKITE_BRANCH=$BUILDKITE_BRANCH \
           -e DIVSHOT_TOKEN=$DIVSHOT_TOKEN \
           -e DIVSHOT_APP=$DIVSHOT_APP \
           -e DIVSHOT_ENV=${DIVSHOT_ENV:-""} \
           --rm --volumes-from divshot-pipeline-data \
           divshot/pipeline-build