#!/usr/bin/env bash

echo "--- Deploying build to ${DIVSHOT_ENV:-'development'} environment"
docker run -e BUILDKITE_BUILD_FOLDER_NAME=$BUILDKITE_BUILD_FOLDER_NAME \
           -e DIVSHOT_ENV=${DIVSHOT_ENV:-"development"} \
           -e DIVSHOT_APP=$DIVSHOT_APP \
           -e DIVSHOT_TOKEN=$DIVSHOT_TOKEN \
           --volumes-from divshot-pipeline-data divshot/pipeline-deploy