#!/usr/bin/env ruby

if ENV['PIPELINE_CACHE_DIRECTORIES'] && ENV['PIPELINE_CACHE_DIRECTORIES'].length > 0
  ENV['PIPELINE_CACHE_DIRECTORIES'].split(";").each do |cache_dir|
    puts ">>> Mounting cached dependencies to #{cache_dir}"
    system("ln -s /home/build/cache/#{cache_dir} /home/build/src/#{cache_dir}")
  end
else
  puts ">>> No cacheable dependencies, proceeding to build."
end